### ISSUE TITLE
Why not use IFileOpenDialog?

### ISSUE THREAD

**Issue by shalva97** [tseli0s/nvdialog#41]
Just a question. The docs of https://learn.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-getopenfilenamea say that they are superseded by `IFileOpenDialog`, So why not use [`IFileOpenDialog`](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifileopendialog) ?

**Comment by tseli0s** [comment]
Correct me if I'm wrong, but isn't `IFileOpenDialog` a C++ class?

**Comment by shalva97** [comment]
I guess its C++ class. Im new to it and wanted to try Kotlin Native so I was wondering why you did not use IFileOpenDialog, because I had access to both of them from Kotlin.

Just to confirm its not possible to use C++ class in C, right?

**Comment by tseli0s** [comment]
I mean, we could workaround it somehow, but it's not like there's any reason to do this as C++ from C requires a layer of "C abstraction" due to different ABIs etc.

If Microsoft completely drops `GetOpenFileNameA` and there's no other C-only alternative _maybe_ I'll do it, but I don't see this happening any time soon.

**Comment by shalva97** [comment]
thanks for the information. will close this ticket then 🚀
